### ISSUE TITLE
problem with unicode rendering in R output

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/repro-tutorial#80]
<img width="448" alt="Screenshot 2021-05-18 at 14 46 56" src="https://user-images.githubusercontent.com/116031/118653575-f9ba5a00-b7e7-11eb-81fb-a469c4b60971.png">

Shouldn't there been green ticks instead of `v`?

**Comment by aaronpeikert** [comment]
I am quite happy that the `cli` package replaces the utf8 symbols with ascii. I can make this work with:

```yaml
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
mainfont: someUTF8compatibleFont
```
and `options(cli.unicode = TRUE)`
Note we have to change the font and use xelatex.
But the mdpi template is decidedly latex (and does not seem to support xelatex) and their font doesn't support a ✓. We'll have to live with this.
